# Generated by Django 6.0.6 on 2026-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('section', models.CharField(choices=[('shop', 'Our Shop'), ('products', 'Our Products'), ('behind', 'Behind the Bakery')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='homepage/videos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
