# Generated by Django 6.0.6 on 2026-09-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemedia',
            name='section',
            field=models.CharField(choices=[('shop', 'Our Shop'), ('products', 'Our Products'), ('behind', 'Behind the Bakery'), ('cakes', 'Cake Gallery')], max_length=20),
        ),
    ]
